### ISSUE TITLE
API not working

### ISSUE THREAD

**Issue by RainbowMiner** [alex-tk/mcm#5]
I just tried out your miner, but it looks like the API is not working.
`mcm.exe -R 1 --api-port 53207 -a cryptonight/2 -o stratum+tcp://cryptonightv8.eu.nicehash.com:3367 -u hereismywalletaddress.miner -p x -t 8 --cpu-affinity 0x0005 --keepalive --av=0`

or

`mcm.exe -R 1 --api-port=53207 -a cryptonight/2 -o stratum+tcp://cryptonightv8.eu.nicehash.com:3367 -u hereismywalletaddress.miner -p x -t 8 --cpu-affinity 0x0005 --keepalive --av=0`

The API is being expected on http://localhost:53207/api.json

**Comment by alex-tk** [comment]
Updated release with enabled api

**Comment by RainbowMiner** [comment]
Confirmed. It works. Thank you :)
