### ISSUE TITLE
Add support for Talleo

### ISSUE THREAD

**Issue by leisegang** [alex-tk/mcm#6]
Could you add suport for talleo

Talleo is a coin similar to Turtle but it uses other settings of miner. 

https://github.com/fireice-uk/xmr-stak/pull/2539/commits/9535f63270585b755453641e41f7b88c4c2e8440 that is a fix for xmr-stak that can be used for implementing to your miner.

**Comment by alex-tk** [comment]
sorry but I don't have plans to add new algos for now
